package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Dayslist generated by hbm2java
 */
public class Dayslist implements java.io.Serializable {

	private Date thisday;

	public Dayslist() {
	}

	public Dayslist(Date thisday) {
		this.thisday = thisday;
	}

	public Date getThisday() {
		return this.thisday;
	}

	public void setThisday(Date thisday) {
		this.thisday = thisday;
	}

}
