package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TlAbsent generated by hbm2java
 */
public class TlAbsent implements java.io.Serializable {

	private int id;
	private String description;
	private Set<TlTaskAbsent> tlTaskAbsents = new HashSet<TlTaskAbsent>(0);

	public TlAbsent() {
	}

	public TlAbsent(int id) {
		this.id = id;
	}

	public TlAbsent(int id, String description, Set<TlTaskAbsent> tlTaskAbsents) {
		this.id = id;
		this.description = description;
		this.tlTaskAbsents = tlTaskAbsents;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<TlTaskAbsent> getTlTaskAbsents() {
		return this.tlTaskAbsents;
	}

	public void setTlTaskAbsents(Set<TlTaskAbsent> tlTaskAbsents) {
		this.tlTaskAbsents = tlTaskAbsents;
	}

}
