package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlCategory generated by hbm2java
 */
public class TlCategory implements java.io.Serializable {

	private String catId;
	private String catDesc;
	private Integer catRefcostperday;

	public TlCategory() {
	}

	public TlCategory(String catId, String catDesc) {
		this.catId = catId;
		this.catDesc = catDesc;
	}

	public TlCategory(String catId, String catDesc, Integer catRefcostperday) {
		this.catId = catId;
		this.catDesc = catDesc;
		this.catRefcostperday = catRefcostperday;
	}

	public String getCatId() {
		return this.catId;
	}

	public void setCatId(String catId) {
		this.catId = catId;
	}

	public String getCatDesc() {
		return this.catDesc;
	}

	public void setCatDesc(String catDesc) {
		this.catDesc = catDesc;
	}

	public Integer getCatRefcostperday() {
		return this.catRefcostperday;
	}

	public void setCatRefcostperday(Integer catRefcostperday) {
		this.catRefcostperday = catRefcostperday;
	}

}
