package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlConvUsername generated by hbm2java
 */
public class TlConvUsername implements java.io.Serializable {

	private TlConvUsernameId id;
	private TlUser tlUser;
	private TlProject tlProject;
	private String otherUsername;

	public TlConvUsername() {
	}

	public TlConvUsername(TlConvUsernameId id, TlUser tlUser,
			TlProject tlProject, String otherUsername) {
		this.id = id;
		this.tlUser = tlUser;
		this.tlProject = tlProject;
		this.otherUsername = otherUsername;
	}

	public TlConvUsernameId getId() {
		return this.id;
	}

	public void setId(TlConvUsernameId id) {
		this.id = id;
	}

	public TlUser getTlUser() {
		return this.tlUser;
	}

	public void setTlUser(TlUser tlUser) {
		this.tlUser = tlUser;
	}

	public TlProject getTlProject() {
		return this.tlProject;
	}

	public void setTlProject(TlProject tlProject) {
		this.tlProject = tlProject;
	}

	public String getOtherUsername() {
		return this.otherUsername;
	}

	public void setOtherUsername(String otherUsername) {
		this.otherUsername = otherUsername;
	}

}
