package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlConvUsernameId generated by hbm2java
 */
public class TlConvUsernameId implements java.io.Serializable {

	private int projectId;
	private String username;

	public TlConvUsernameId() {
	}

	public TlConvUsernameId(int projectId, String username) {
		this.projectId = projectId;
		this.username = username;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TlConvUsernameId))
			return false;
		TlConvUsernameId castOther = (TlConvUsernameId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
