package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TlCustomer generated by hbm2java
 */
public class TlCustomer implements java.io.Serializable {

	private String custId;
	private String custDesc;
	private Set<TlTask> tlTasks = new HashSet<TlTask>(0);
	private Set<TlProject> tlProjects = new HashSet<TlProject>(0);

	public TlCustomer() {
	}

	public TlCustomer(String custId, String custDesc) {
		this.custId = custId;
		this.custDesc = custDesc;
	}

	public TlCustomer(String custId, String custDesc, Set<TlTask> tlTasks,
			Set<TlProject> tlProjects) {
		this.custId = custId;
		this.custDesc = custDesc;
		this.tlTasks = tlTasks;
		this.tlProjects = tlProjects;
	}

	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getCustDesc() {
		return this.custDesc;
	}

	public void setCustDesc(String custDesc) {
		this.custDesc = custDesc;
	}

	public Set<TlTask> getTlTasks() {
		return this.tlTasks;
	}

	public void setTlTasks(Set<TlTask> tlTasks) {
		this.tlTasks = tlTasks;
	}

	public Set<TlProject> getTlProjects() {
		return this.tlProjects;
	}

	public void setTlProjects(Set<TlProject> tlProjects) {
		this.tlProjects = tlProjects;
	}

}
