package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TlProject generated by hbm2java
 */
public class TlProject implements java.io.Serializable {

	private int projectId;
	private TlQueue tlQueue;
	private TlUser tlUser;
	private TlCustomer tlCustomer;
	private String projectDesc;
	private Character projectType;
	private Date projectStartdate;
	private Date projectEnddate;
	private BigDecimal projectHrbudget;
	private Date projectDeadline;
	private Boolean active;
	private String obs;
	private Set<TlTask> tlTasks = new HashSet<TlTask>(0);
	private Set<TlConvUsername> tlConvUsernames = new HashSet<TlConvUsername>(0);

	public TlProject() {
	}

	public TlProject(int projectId, TlUser tlUser, String projectDesc,
			BigDecimal projectHrbudget, Date projectDeadline) {
		this.projectId = projectId;
		this.tlUser = tlUser;
		this.projectDesc = projectDesc;
		this.projectHrbudget = projectHrbudget;
		this.projectDeadline = projectDeadline;
	}

	public TlProject(int projectId, TlQueue tlQueue, TlUser tlUser,
			TlCustomer tlCustomer, String projectDesc, Character projectType,
			Date projectStartdate, Date projectEnddate,
			BigDecimal projectHrbudget, Date projectDeadline, Boolean active,
			String obs, Set<TlTask> tlTasks, Set<TlConvUsername> tlConvUsernames) {
		this.projectId = projectId;
		this.tlQueue = tlQueue;
		this.tlUser = tlUser;
		this.tlCustomer = tlCustomer;
		this.projectDesc = projectDesc;
		this.projectType = projectType;
		this.projectStartdate = projectStartdate;
		this.projectEnddate = projectEnddate;
		this.projectHrbudget = projectHrbudget;
		this.projectDeadline = projectDeadline;
		this.active = active;
		this.obs = obs;
		this.tlTasks = tlTasks;
		this.tlConvUsernames = tlConvUsernames;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public TlQueue getTlQueue() {
		return this.tlQueue;
	}

	public void setTlQueue(TlQueue tlQueue) {
		this.tlQueue = tlQueue;
	}

	public TlUser getTlUser() {
		return this.tlUser;
	}

	public void setTlUser(TlUser tlUser) {
		this.tlUser = tlUser;
	}

	public TlCustomer getTlCustomer() {
		return this.tlCustomer;
	}

	public void setTlCustomer(TlCustomer tlCustomer) {
		this.tlCustomer = tlCustomer;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public Character getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Character projectType) {
		this.projectType = projectType;
	}

	public Date getProjectStartdate() {
		return this.projectStartdate;
	}

	public void setProjectStartdate(Date projectStartdate) {
		this.projectStartdate = projectStartdate;
	}

	public Date getProjectEnddate() {
		return this.projectEnddate;
	}

	public void setProjectEnddate(Date projectEnddate) {
		this.projectEnddate = projectEnddate;
	}

	public BigDecimal getProjectHrbudget() {
		return this.projectHrbudget;
	}

	public void setProjectHrbudget(BigDecimal projectHrbudget) {
		this.projectHrbudget = projectHrbudget;
	}

	public Date getProjectDeadline() {
		return this.projectDeadline;
	}

	public void setProjectDeadline(Date projectDeadline) {
		this.projectDeadline = projectDeadline;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public Set<TlTask> getTlTasks() {
		return this.tlTasks;
	}

	public void setTlTasks(Set<TlTask> tlTasks) {
		this.tlTasks = tlTasks;
	}

	public Set<TlConvUsername> getTlConvUsernames() {
		return this.tlConvUsernames;
	}

	public void setTlConvUsernames(Set<TlConvUsername> tlConvUsernames) {
		this.tlConvUsernames = tlConvUsernames;
	}

}
