package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TlQueue generated by hbm2java
 */
public class TlQueue implements java.io.Serializable {

	private int queueId;
	private String queueName;
	private Set<TlProject> tlProjects = new HashSet<TlProject>(0);

	public TlQueue() {
	}

	public TlQueue(int queueId) {
		this.queueId = queueId;
	}

	public TlQueue(int queueId, String queueName, Set<TlProject> tlProjects) {
		this.queueId = queueId;
		this.queueName = queueName;
		this.tlProjects = tlProjects;
	}

	public int getQueueId() {
		return this.queueId;
	}

	public void setQueueId(int queueId) {
		this.queueId = queueId;
	}

	public String getQueueName() {
		return this.queueName;
	}

	public void setQueueName(String queueName) {
		this.queueName = queueName;
	}

	public Set<TlProject> getTlProjects() {
		return this.tlProjects;
	}

	public void setTlProjects(Set<TlProject> tlProjects) {
		this.tlProjects = tlProjects;
	}

}
