package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TlTask generated by hbm2java
 */
public class TlTask implements java.io.Serializable {

	private int taskId;
	private TlProject tlProject;
	private TlCustomer tlCustomer;
	private String taskDesc;
	private Date startDate;
	private Date endDate;
	private String resource1Cat;
	private BigDecimal resource1Days;
	private String resource2Cat;
	private BigDecimal recource2Days;
	private String resource3Cat;
	private BigDecimal resource3Days;
	private char taskStatus;
	private Character tasktype;
	private Short queue;
	private String taskVisibility;
	private String taskSource;
	private Date plannedStart;
	private Date plannedEnd;
	private Long timeBudget;
	private BigDecimal moneyBudget;
	private Set<TlWorkdone> tlWorkdones = new HashSet<TlWorkdone>(0);
	private Set<TlUser> tlUsers = new HashSet<TlUser>(0);
	private TlTaskAbsent tlTaskAbsent;
	private TlTaskTicket tlTaskTicket;

	public TlTask() {
	}

	public TlTask(int taskId, TlProject tlProject, String taskDesc,
			char taskStatus) {
		this.taskId = taskId;
		this.tlProject = tlProject;
		this.taskDesc = taskDesc;
		this.taskStatus = taskStatus;
	}

	public TlTask(int taskId, TlProject tlProject, TlCustomer tlCustomer,
			String taskDesc, Date startDate, Date endDate, String resource1Cat,
			BigDecimal resource1Days, String resource2Cat,
			BigDecimal recource2Days, String resource3Cat,
			BigDecimal resource3Days, char taskStatus, Character tasktype,
			Short queue, String taskVisibility, String taskSource,
			Date plannedStart, Date plannedEnd, Long timeBudget,
			BigDecimal moneyBudget, Set<TlWorkdone> tlWorkdones,
			Set<TlUser> tlUsers, TlTaskAbsent tlTaskAbsent,
			TlTaskTicket tlTaskTicket) {
		this.taskId = taskId;
		this.tlProject = tlProject;
		this.tlCustomer = tlCustomer;
		this.taskDesc = taskDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.resource1Cat = resource1Cat;
		this.resource1Days = resource1Days;
		this.resource2Cat = resource2Cat;
		this.recource2Days = recource2Days;
		this.resource3Cat = resource3Cat;
		this.resource3Days = resource3Days;
		this.taskStatus = taskStatus;
		this.tasktype = tasktype;
		this.queue = queue;
		this.taskVisibility = taskVisibility;
		this.taskSource = taskSource;
		this.plannedStart = plannedStart;
		this.plannedEnd = plannedEnd;
		this.timeBudget = timeBudget;
		this.moneyBudget = moneyBudget;
		this.tlWorkdones = tlWorkdones;
		this.tlUsers = tlUsers;
		this.tlTaskAbsent = tlTaskAbsent;
		this.tlTaskTicket = tlTaskTicket;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public TlProject getTlProject() {
		return this.tlProject;
	}

	public void setTlProject(TlProject tlProject) {
		this.tlProject = tlProject;
	}

	public TlCustomer getTlCustomer() {
		return this.tlCustomer;
	}

	public void setTlCustomer(TlCustomer tlCustomer) {
		this.tlCustomer = tlCustomer;
	}

	public String getTaskDesc() {
		return this.taskDesc;
	}

	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getResource1Cat() {
		return this.resource1Cat;
	}

	public void setResource1Cat(String resource1Cat) {
		this.resource1Cat = resource1Cat;
	}

	public BigDecimal getResource1Days() {
		return this.resource1Days;
	}

	public void setResource1Days(BigDecimal resource1Days) {
		this.resource1Days = resource1Days;
	}

	public String getResource2Cat() {
		return this.resource2Cat;
	}

	public void setResource2Cat(String resource2Cat) {
		this.resource2Cat = resource2Cat;
	}

	public BigDecimal getRecource2Days() {
		return this.recource2Days;
	}

	public void setRecource2Days(BigDecimal recource2Days) {
		this.recource2Days = recource2Days;
	}

	public String getResource3Cat() {
		return this.resource3Cat;
	}

	public void setResource3Cat(String resource3Cat) {
		this.resource3Cat = resource3Cat;
	}

	public BigDecimal getResource3Days() {
		return this.resource3Days;
	}

	public void setResource3Days(BigDecimal resource3Days) {
		this.resource3Days = resource3Days;
	}

	public char getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(char taskStatus) {
		this.taskStatus = taskStatus;
	}

	public Character getTasktype() {
		return this.tasktype;
	}

	public void setTasktype(Character tasktype) {
		this.tasktype = tasktype;
	}

	public Short getQueue() {
		return this.queue;
	}

	public void setQueue(Short queue) {
		this.queue = queue;
	}

	public String getTaskVisibility() {
		return this.taskVisibility;
	}

	public void setTaskVisibility(String taskVisibility) {
		this.taskVisibility = taskVisibility;
	}

	public String getTaskSource() {
		return this.taskSource;
	}

	public void setTaskSource(String taskSource) {
		this.taskSource = taskSource;
	}

	public Date getPlannedStart() {
		return this.plannedStart;
	}

	public void setPlannedStart(Date plannedStart) {
		this.plannedStart = plannedStart;
	}

	public Date getPlannedEnd() {
		return this.plannedEnd;
	}

	public void setPlannedEnd(Date plannedEnd) {
		this.plannedEnd = plannedEnd;
	}

	public Long getTimeBudget() {
		return this.timeBudget;
	}

	public void setTimeBudget(Long timeBudget) {
		this.timeBudget = timeBudget;
	}

	public BigDecimal getMoneyBudget() {
		return this.moneyBudget;
	}

	public void setMoneyBudget(BigDecimal moneyBudget) {
		this.moneyBudget = moneyBudget;
	}

	public Set<TlWorkdone> getTlWorkdones() {
		return this.tlWorkdones;
	}

	public void setTlWorkdones(Set<TlWorkdone> tlWorkdones) {
		this.tlWorkdones = tlWorkdones;
	}

	public Set<TlUser> getTlUsers() {
		return this.tlUsers;
	}

	public void setTlUsers(Set<TlUser> tlUsers) {
		this.tlUsers = tlUsers;
	}

	public TlTaskAbsent getTlTaskAbsent() {
		return this.tlTaskAbsent;
	}

	public void setTlTaskAbsent(TlTaskAbsent tlTaskAbsent) {
		this.tlTaskAbsent = tlTaskAbsent;
	}

	public TlTaskTicket getTlTaskTicket() {
		return this.tlTaskTicket;
	}

	public void setTlTaskTicket(TlTaskTicket tlTaskTicket) {
		this.tlTaskTicket = tlTaskTicket;
	}

}
