package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlTaskAbsent generated by hbm2java
 */
public class TlTaskAbsent implements java.io.Serializable {

	private int taskId;
	private TlAbsent tlAbsent;
	private TlTask tlTask;
	private String isMissingToWork;
	private boolean isVacation;

	public TlTaskAbsent() {
	}

	public TlTaskAbsent(TlAbsent tlAbsent, TlTask tlTask,
			String isMissingToWork, boolean isVacation) {
		this.tlAbsent = tlAbsent;
		this.tlTask = tlTask;
		this.isMissingToWork = isMissingToWork;
		this.isVacation = isVacation;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public TlAbsent getTlAbsent() {
		return this.tlAbsent;
	}

	public void setTlAbsent(TlAbsent tlAbsent) {
		this.tlAbsent = tlAbsent;
	}

	public TlTask getTlTask() {
		return this.tlTask;
	}

	public void setTlTask(TlTask tlTask) {
		this.tlTask = tlTask;
	}

	public String getIsMissingToWork() {
		return this.isMissingToWork;
	}

	public void setIsMissingToWork(String isMissingToWork) {
		this.isMissingToWork = isMissingToWork;
	}

	public boolean isIsVacation() {
		return this.isVacation;
	}

	public void setIsVacation(boolean isVacation) {
		this.isVacation = isVacation;
	}

}
