package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlTaskTicket generated by hbm2java
 */
public class TlTaskTicket implements java.io.Serializable {

	private int taskId;
	private TlTask tlTask;
	private int ticketId;

	public TlTaskTicket() {
	}

	public TlTaskTicket(TlTask tlTask, int ticketId) {
		this.tlTask = tlTask;
		this.ticketId = ticketId;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public TlTask getTlTask() {
		return this.tlTask;
	}

	public void setTlTask(TlTask tlTask) {
		this.tlTask = tlTask;
	}

	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

}
