package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TlUser generated by hbm2java
 */
public class TlUser implements java.io.Serializable {

	private String username;
	private String catId;
	private String email;
	private boolean disabled;
	private Date disableDate;
	private Date enabledDate;
	private BigDecimal hoursperday;
	private String primaveraEmployeeId;
	private Set<TlProject> tlProjects = new HashSet<TlProject>(0);
	private Set<TlConvUsername> tlConvUsernames = new HashSet<TlConvUsername>(0);
	private Set<TlWorkday> tlWorkdays = new HashSet<TlWorkday>(0);
	private Set<TlTask> tlTasks = new HashSet<TlTask>(0);

	public TlUser() {
	}

	public TlUser(String username, String catId, boolean disabled,
			Date enabledDate, BigDecimal hoursperday) {
		this.username = username;
		this.catId = catId;
		this.disabled = disabled;
		this.enabledDate = enabledDate;
		this.hoursperday = hoursperday;
	}

	public TlUser(String username, String catId, String email,
			boolean disabled, Date disableDate, Date enabledDate,
			BigDecimal hoursperday, String primaveraEmployeeId,
			Set<TlProject> tlProjects, Set<TlConvUsername> tlConvUsernames,
			Set<TlWorkday> tlWorkdays, Set<TlTask> tlTasks) {
		this.username = username;
		this.catId = catId;
		this.email = email;
		this.disabled = disabled;
		this.disableDate = disableDate;
		this.enabledDate = enabledDate;
		this.hoursperday = hoursperday;
		this.primaveraEmployeeId = primaveraEmployeeId;
		this.tlProjects = tlProjects;
		this.tlConvUsernames = tlConvUsernames;
		this.tlWorkdays = tlWorkdays;
		this.tlTasks = tlTasks;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCatId() {
		return this.catId;
	}

	public void setCatId(String catId) {
		this.catId = catId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isDisabled() {
		return this.disabled;
	}

	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}

	public Date getDisableDate() {
		return this.disableDate;
	}

	public void setDisableDate(Date disableDate) {
		this.disableDate = disableDate;
	}

	public Date getEnabledDate() {
		return this.enabledDate;
	}

	public void setEnabledDate(Date enabledDate) {
		this.enabledDate = enabledDate;
	}

	public BigDecimal getHoursperday() {
		return this.hoursperday;
	}

	public void setHoursperday(BigDecimal hoursperday) {
		this.hoursperday = hoursperday;
	}

	public String getPrimaveraEmployeeId() {
		return this.primaveraEmployeeId;
	}

	public void setPrimaveraEmployeeId(String primaveraEmployeeId) {
		this.primaveraEmployeeId = primaveraEmployeeId;
	}

	public Set<TlProject> getTlProjects() {
		return this.tlProjects;
	}

	public void setTlProjects(Set<TlProject> tlProjects) {
		this.tlProjects = tlProjects;
	}

	public Set<TlConvUsername> getTlConvUsernames() {
		return this.tlConvUsernames;
	}

	public void setTlConvUsernames(Set<TlConvUsername> tlConvUsernames) {
		this.tlConvUsernames = tlConvUsernames;
	}

	public Set<TlWorkday> getTlWorkdays() {
		return this.tlWorkdays;
	}

	public void setTlWorkdays(Set<TlWorkday> tlWorkdays) {
		this.tlWorkdays = tlWorkdays;
	}

	public Set<TlTask> getTlTasks() {
		return this.tlTasks;
	}

	public void setTlTasks(Set<TlTask> tlTasks) {
		this.tlTasks = tlTasks;
	}

}
