package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlWorkdoneId generated by hbm2java
 */
public class TlWorkdoneId implements java.io.Serializable {

	private int workdayId;
	private short workIdx;

	public TlWorkdoneId() {
	}

	public TlWorkdoneId(int workdayId, short workIdx) {
		this.workdayId = workdayId;
		this.workIdx = workIdx;
	}

	public int getWorkdayId() {
		return this.workdayId;
	}

	public void setWorkdayId(int workdayId) {
		this.workdayId = workdayId;
	}

	public short getWorkIdx() {
		return this.workIdx;
	}

	public void setWorkIdx(short workIdx) {
		this.workIdx = workIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TlWorkdoneId))
			return false;
		TlWorkdoneId castOther = (TlWorkdoneId) other;

		return (this.getWorkdayId() == castOther.getWorkdayId())
				&& (this.getWorkIdx() == castOther.getWorkIdx());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkdayId();
		result = 37 * result + this.getWorkIdx();
		return result;
	}

}
