package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * TlWorkdone generated by hbm2java
 */
public class TlWorkdone implements java.io.Serializable {

	private TlWorkdoneId id;
	private TlWorkday tlWorkday;
	private TlTask tlTask;
	private String workdoneDesc;
	private Long spentTime;

	public TlWorkdone() {
	}

	public TlWorkdone(TlWorkdoneId id, TlWorkday tlWorkday, TlTask tlTask) {
		this.id = id;
		this.tlWorkday = tlWorkday;
		this.tlTask = tlTask;
	}

	public TlWorkdone(TlWorkdoneId id, TlWorkday tlWorkday, TlTask tlTask,
			String workdoneDesc, Long spentTime) {
		this.id = id;
		this.tlWorkday = tlWorkday;
		this.tlTask = tlTask;
		this.workdoneDesc = workdoneDesc;
		this.spentTime = spentTime;
	}

	public TlWorkdoneId getId() {
		return this.id;
	}

	public void setId(TlWorkdoneId id) {
		this.id = id;
	}

	public TlWorkday getTlWorkday() {
		return this.tlWorkday;
	}

	public void setTlWorkday(TlWorkday tlWorkday) {
		this.tlWorkday = tlWorkday;
	}

	public TlTask getTlTask() {
		return this.tlTask;
	}

	public void setTlTask(TlTask tlTask) {
		this.tlTask = tlTask;
	}

	public String getWorkdoneDesc() {
		return this.workdoneDesc;
	}

	public void setWorkdoneDesc(String workdoneDesc) {
		this.workdoneDesc = workdoneDesc;
	}

	public Long getSpentTime() {
		return this.spentTime;
	}

	public void setSpentTime(Long spentTime) {
		this.spentTime = spentTime;
	}

}
