package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TlWorkday generated by hbm2java
 */
public class TlWorkday implements java.io.Serializable {

	private int workdayId;
	private TlUser tlUser;
	private Date day;
	private Date entryhour;
	private String obs;
	private Set<TlWorkdone> tlWorkdones = new HashSet<TlWorkdone>(0);

	public TlWorkday() {
	}

	public TlWorkday(int workdayId, Date day, Date entryhour) {
		this.workdayId = workdayId;
		this.day = day;
		this.entryhour = entryhour;
	}

	public TlWorkday(int workdayId, TlUser tlUser, Date day, Date entryhour,
			String obs, Set<TlWorkdone> tlWorkdones) {
		this.workdayId = workdayId;
		this.tlUser = tlUser;
		this.day = day;
		this.entryhour = entryhour;
		this.obs = obs;
		this.tlWorkdones = tlWorkdones;
	}

	public int getWorkdayId() {
		return this.workdayId;
	}

	public void setWorkdayId(int workdayId) {
		this.workdayId = workdayId;
	}

	public TlUser getTlUser() {
		return this.tlUser;
	}

	public void setTlUser(TlUser tlUser) {
		this.tlUser = tlUser;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public Date getEntryhour() {
		return this.entryhour;
	}

	public void setEntryhour(Date entryhour) {
		this.entryhour = entryhour;
	}

	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public Set<TlWorkdone> getTlWorkdones() {
		return this.tlWorkdones;
	}

	public void setTlWorkdones(Set<TlWorkdone> tlWorkdones) {
		this.tlWorkdones = tlWorkdones;
	}

}
