package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

/**
 * Usrsreachtime generated by hbm2java
 */
public class Usrsreachtime implements java.io.Serializable {

	private UsrsreachtimeId id;

	public Usrsreachtime() {
	}

	public Usrsreachtime(UsrsreachtimeId id) {
		this.id = id;
	}

	public UsrsreachtimeId getId() {
		return this.id;
	}

	public void setId(UsrsreachtimeId id) {
		this.id = id;
	}

}
