package pt.moredata.jpa.taskman.entities;

// Generated 19/08/2013 22:12:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsrsreachtimeId generated by hbm2java
 */
public class UsrsreachtimeId implements java.io.Serializable {

	private String users;
	private Date reachpagetime;
	private String pagedesc;

	public UsrsreachtimeId() {
	}

	public UsrsreachtimeId(String users, Date reachpagetime, String pagedesc) {
		this.users = users;
		this.reachpagetime = reachpagetime;
		this.pagedesc = pagedesc;
	}

	public String getUsers() {
		return this.users;
	}

	public void setUsers(String users) {
		this.users = users;
	}

	public Date getReachpagetime() {
		return this.reachpagetime;
	}

	public void setReachpagetime(Date reachpagetime) {
		this.reachpagetime = reachpagetime;
	}

	public String getPagedesc() {
		return this.pagedesc;
	}

	public void setPagedesc(String pagedesc) {
		this.pagedesc = pagedesc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsrsreachtimeId))
			return false;
		UsrsreachtimeId castOther = (UsrsreachtimeId) other;

		return ((this.getUsers() == castOther.getUsers()) || (this.getUsers() != null
				&& castOther.getUsers() != null && this.getUsers().equals(
				castOther.getUsers())))
				&& ((this.getReachpagetime() == castOther.getReachpagetime()) || (this
						.getReachpagetime() != null
						&& castOther.getReachpagetime() != null && this
						.getReachpagetime()
						.equals(castOther.getReachpagetime())))
				&& ((this.getPagedesc() == castOther.getPagedesc()) || (this
						.getPagedesc() != null
						&& castOther.getPagedesc() != null && this
						.getPagedesc().equals(castOther.getPagedesc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsers() == null ? 0 : this.getUsers().hashCode());
		result = 37
				* result
				+ (getReachpagetime() == null ? 0 : this.getReachpagetime()
						.hashCode());
		result = 37 * result
				+ (getPagedesc() == null ? 0 : this.getPagedesc().hashCode());
		return result;
	}

}
